dist: trusty
sudo: false
branches:
  except:
    - trunk
language: c++
compiler:
  - gcc
addons:
  apt:
    packages:
      - texinfo # for makeinfo
      - intltool # for intltoolize
      - swig
      - doxygen
      - libboost-all-dev
      - guile-2.0-dev
      - libaqbanking-dev
      - libdbi-dev
      - libdbd-sqlite3
      - libglib2.0-dev
      - libgnomecanvas2-dev
      - libgtk2.0-dev
      - libofx-dev
      - libwebkit-dev
      - libxml2-dev
      - libxslt1-dev
      - python
      - python-dev
      - xsltproc
      - zlib1g-dev
install:
  - git clone https://github.com/google/googletest -b release-1.8.0 ~/gtest
env:
  global:
    - GTEST_ROOT=~/gtest/googletest
    - GMOCK_ROOT=~/gtest/googlemock
    - TZ="America/Los_Angeles"
  matrix:
    - TRAVIS_USE_CMAKE=true
    - TRAVIS_USE_CMAKE=false
script: >
  if [ ${TRAVIS_USE_CMAKE} = "true" ]; then
    mkdir build &&
    cd build &&
    cmake ../ &&
    make &&
    make check
  else
    ./autogen.sh &&
    ./configure --enable-python --enable-doxygen &&
    make &&
    make doc &&
    make check
  fi
cache:
  - ~/gtest
